# Generated by Django 4.1.2 on 2023-01-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='Title',
        ),
    ]
