# Generated by Django 4.1.2 on 2023-03-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
            ],
        ),
    ]
