# Generated by Django 4.1.2 on 2023-03-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='Title',
            field=models.CharField(default='=1', max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
