# Generated by Django 4.1.2 on 2023-03-07 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('firstname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('middlename', models.TextField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloodtype', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'O'), ('4', 'A+'), ('5', 'B+'), ('6', 'O+'), ('7', 'A-'), ('7', 'B-'), ('7', 'O-')], default=3, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='kal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField(max_length=25)),
                ('Age', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('middlename', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloodtype', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'O'), ('4', 'A+'), ('5', 'B+'), ('6', 'O+'), ('7', 'A-'), ('7', 'B-'), ('7', 'O-')], default=3, max_length=10)),
                ('zone', models.CharField(max_length=20)),
                ('woreda', models.CharField(max_length=20)),
                ('kebele', models.CharField(max_length=20)),
                ('vaccine_id', models.IntegerField(default=0)),
                ('mother_id', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='mother_vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('1', 'TT1'), ('2', 'TT2'), ('3', 'TT3'), ('4', 'TT4'), ('5', 'TT5'), ('6', 'RH')], max_length=10)),
                ('vaccine_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_id', models.IntegerField(default=0)),
                ('product_price', models.FloatField(default=0.0)),
            ],
            options={
                'permissions': [('can_change_vaccine_catagory', 'change catagory')],
            },
        ),
        migrations.CreateModel(
            name='child_vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('1', 'R1'), ('2', 'R2'), ('3', 'R3'), ('4', 'R4'), ('5', 'R5')], max_length=10)),
                ('child_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.child')),
            ],
        ),
    ]
